elastic:
  directories:
    - rules
    - rules_building_block
  recursive_directories: true
  rule_glob_pattern: '*.toml'


splunk:
  directories:
    - rules
    - rules_building_block
  recursive_directories: true
  rule_glob_pattern: '*.yml'

sigma:
  directories:
    - rules
    - rules_building_block
  recursive_directories: true
  rule_glob_pattern: '*.yml'
